CREATE TABLE gear_credit_log(
  id SERIAL PRIMARY KEY,
  gear_id INT NOT NULL REFERENCES gear,
  credit INT NOT NULL,
  accumulated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  comment VARCHAR(16) NOT NULL
);